Add touches controls
apomelitos/2048-typescript pull request #12
Opened 2022-02-17 10:40 UTC by apomelitos

2022-02-17 11:34 UTC, mrlika requested changes

2022-02-17 11:34 UTC, mrlika commented on src/hooks/useHandleTouches.ts
> +  const [startCoords, setStartCoords] = useState<Coords | null>(null);
`startCoords` doesn't participate in rendering is not a dependency of a hook. It means that it is better to implement it as `Ref`

2022-02-17 13:43 UTC, mrlika requested changes

2022-02-17 13:43 UTC, mrlika commented on src/components/Game.tsx
> +  const [onTouchStart, onTouchEnd] = useHandleTouches((dir) => updateState(dir));
This line can be simplified to `const [onTouchStart, onTouchEnd] = useHandleTouches(updateState);`

2022-02-18 08:29 UTC, mrlika requested changes

2022-02-18 08:29 UTC, mrlika commented on src/utils/gameUtils.ts
> +    console.log('Hello');
Remove `console` statement

2022-02-18 08:32 UTC, TheForsakenSpirit approved these changes

2022-02-18 08:50 UTC, apomelitos commented on src/utils/gameUtils.ts
> +    console.log('Hello');
Already removed in the last commit [961ab3d](https://github.com/apomelitos/2048-typescript/pull/12/commits/961ab3d3cb90127f53aa65638c6d394a6e29b4c4)

2022-02-18 09:01 UTC, mrlika approved these changes

2022-02-18 09:01 UTC, merged