Add useKeyPress hook for subscribing to keyboard events
apomelitos/2048-typescript pull request #6
Opened 2022-02-08 10:30 UTC by apomelitos

2022-02-08 11:20 UTC, TheForsakenSpirit requested changes

2022-02-08 11:20 UTC, TheForsakenSpirit commented on src/components/Game.tsx
> +  useKeyPress('ArrowDown', moveDown);
hide to one effect

2022-02-09 11:00 UTC, TheForsakenSpirit requested changes

2022-02-09 11:00 UTC, TheForsakenSpirit commented on src/hooks/useHandleButtons.ts
> +  }
Try to do this in one line with `new Array`, `fill` and `map`

2022-02-09 11:00 UTC, TheForsakenSpirit commented on src/hooks/useHandleButtons.ts
> +    getTile = getTileFromCol;
Avoid switching between function in one variable. Specialty mixing input data.

2022-02-09 11:30 UTC, mrlika requested changes

2022-02-09 11:30 UTC, mrlika commented on src/hooks/useHandleButtons.ts
> +    id: Date.now(),
`Date.now()` depends on OS time. It means that I may break the game by changing OS time. Use `perfomance.now()` instead

2022-02-09 11:30 UTC, mrlika commented on src/hooks/useHandleButtons.ts
> +  console.log(emptyCellsPositions);
Don't push `console` statements into production

2022-02-09 11:30 UTC, mrlika commented on src/hooks/useHandleButtons.ts
> +  }
The algorithm doesn't look correct. We will figure out this next week.

2022-02-11 09:31 UTC, TheForsakenSpirit requested changes

2022-02-11 09:31 UTC, TheForsakenSpirit commented on src/hooks/useHandleButtons.ts
> +      const getNextPositionInRow = (pointer: number, idx: number): Position => [idx, pointer];
use one method to access.

2022-02-11 09:31 UTC, TheForsakenSpirit commented on src/hooks/useHandleButtons.ts
> +        options.getNextPosition = getNextPositionInRow;
if you want conditional inverting access, create proxy-method that will conditionally invert column and row

2022-02-14 10:56 UTC, TheForsakenSpirit approved these changes

2022-02-14 13:21 UTC, TheForsakenSpirit approved these changes

2022-02-14 14:10 UTC, mrlika approved these changes

2022-02-14 14:13 UTC, merged